image:
  file: .gitpod.dockerfile
# tasks:
#   - init: echo "Starting REPL"
#     command: clojure -Sdeps '{:deps {nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.23.0"}}}'  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
vscode:
  extensions:
    - betterthantomorrow.calva@2.0.135:Hqx+7c3IPVpoaKHU7sL6bA==
    - borkdude.clj-kondo@2020.11.7:kJKMthksl/DZXwa7g4wgkg==