
image:
  file: .gitpod.dockerfile


vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
  - name: Prepare deps
    init: clojure -P -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.26.0"}}}'
  - name: README
    command: open -g README.md