image:
  file: .gitpod.dockerfile

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - betterthantomorrow.calva


tasks:
  #- name: Fix blank swing window problem
  #  init: eval $(gp env JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false)
  - name: Fix blank swing window problem
    init: echo export JAVA_TOOL_OPTIONS=\"$JAVA_TOOL_OPTIONS -Dsun.java2d.xrender=false\" >> /home/gitpod/.bashrc
    command: source /home/gitpod/.bashrc
  - name: Prepare deps
    init: clojure -P -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"0.8.3"},cider/cider-nrepl {:mvn/version,"0.26.0"}}}'
  - name: Open README
    command: open -g README.md
  - name: Echo done
    command: echo "Tasks done"

# source /home/gitpod/.bashrc # && mvn package && java -jar target/*with-dependencies.jar%